sudo: false

language: node_js

node_js:
  - "4"
  - "6"
  - stable

install:
  - npm install
  - npm install typescript coffee-script

script:
  - make lint depcruise cover
  - npm run nsp

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
    code_climate:
        repo_token: 9a7b8236757774b2d7b458a798bee1d3e72aaa3044a029bfa1428948941cf854
